apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-janitor
  namespace: log-system
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: janitor
            image: busybox
            command: ["/bin/sh", "-c"]
            args: ["find /mnt/logs -name '*.log' -mtime +7 -delete && find /mnt/logs -type d -empty -delete"]
            volumeMounts:
              - name: log-storage
                mountPath: /mnt/logs
          restartPolicy: OnFailure
          volumes:
            - name: log-storage
              persistentVolumeClaim:
                claimName: log-nfs-pvc
