image:
  repository: localhost:5000/neuralog
  tag: "dev"
  pullPolicy: Always

storage:
  storageClassName: "local-path"
  storageSize: 5Gi
  accessMode: ReadWriteOnce

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false

retention:
  days: 7

collector:
  redactEnabled: "true"

autoscaling:
  enabled: false

networkPolicy:
  enabled: false
